package Tournament;

import java.util.List;

public class Fitness {
    /**
     * Fitness function that checks if number of outputs is correct
     * @param size - list of results generated by program
     * @param expectedSize - list of expected results
     * @return fitness score
     */
    public static double fitnessOutput(int size, int expectedSize) {
        return Math.abs(expectedSize - size);
    }

    /**
     * Fitness function that checks if results are input sensitive
     * @param results - list of results generated by program
     * @return fitness score
     */
    public static double fitnessSensitivity(List<Integer> results) {
        double fitness = 0;
        double meanValue = 0;
        for(int result: results) {
            meanValue += result;
        }
        meanValue /= results.size();

        for(int result: results) {
            fitness += result - meanValue;
        }

        return 1 / (fitness / results.size());
    }

    /**
     * Fitness function that checks whether any of the results meet any of the expected results
     * @param results - list of results generated by program
     * @param expectedResults - list of expected results
     * @return fitness score
     */
    public static double fitnessResult(List<Integer> results, List<Integer> expectedResults) {
        double fitness = Double.MAX_VALUE;
        for(int result: results) {
            for(int expectedResult: expectedResults) {
                int diff = Math.abs(expectedResult - result);
                fitness = diff < fitness ? diff : fitness;
            }
        }
        return 1 / fitness;
    }
}
